#!/bin/bash

if [[ $(whoami) != root ]]; then
  echo "You must run this script as root (using sudo)"
  exit
fi

cd /opt/scsc

echo ">>> Updating SCSC"
git pull

echo ">>> Running Chef"
chef-solo -c solo.rb -j nodes/scsc.json
