depends "openvpn"
depends "apt"
depends "apache2"
depends "i2p"
depends "znc"
depends "monit"
depends "btsync"
depends "subsonic"
depends "firefox-sync"
depends "coldsweat"
depends "poche"
depends "folders"

supports "ubuntu"
